### ISSUE TITLE
Proto13.2 file format

### ISSUE THREAD

**Issue by kg9316** [m5stack/M5_Hardware#1]
Hi, we have problems importing the file, out software tells us that "the Altium file needs to be in ascii format with UTF-8 encoding"
Could you please export the file in this format ?

**Comment by imliubo** [comment]
Hi @kg9316 ,

Sorry for this very late reply, our hardware engineer said you can try [Module-Type-A.PcbDoc file](https://github.com/m5stack/M5_Hardware/blob/master/PCB/Module/Module-Type-A.PcbDoc).

I will close this issues, feel free to reopen this if you still have problem.
